application: your-application-id
version: 1
runtime: python
api_version: 1

inbound_services:
- mail




handlers:
- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /testdata
  static_dir: static/testdata

- url: /tasks/train
  script: suggester.py
  login: admin

- url: /tasks/suggest
  script: suggester.py
  login: admin

- url: /_ah/mail/.+
  script: aggregator/mail.py
  login: admin

- url: /resources/v1/.*
  script: api/handler.py

- url: /oauth.*
  script: oauth.py
  login: admin

- url: /ds_reset
  script: ds_reset.py
  login: admin

- url: /.*
  script: main.py
